# Generated by Django 4.2.3 on 2023-09-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moodsic', '0002_rename_date_moodsic_searchdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodsic',
            name='searchDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
